// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTZdtENx2e4QpJXXK-Sb3yIUdrv89ZmU',
    appId: '1:393420910142:web:3ba0cd7f09bb8f105a2b6f',
    messagingSenderId: '393420910142',
    projectId: 'news-3d5f9',
    authDomain: 'news-3d5f9.firebaseapp.com',
    storageBucket: 'news-3d5f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0f014YCOuvZP4qBjpY2ZngbJRapE9d3U',
    appId: '1:393420910142:android:65d52e3e638c9a7f5a2b6f',
    messagingSenderId: '393420910142',
    projectId: 'news-3d5f9',
    storageBucket: 'news-3d5f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXA6HxURDrX5AexVtHCQfR95O4LgeyxmM',
    appId: '1:393420910142:ios:1579257a746300515a2b6f',
    messagingSenderId: '393420910142',
    projectId: 'news-3d5f9',
    storageBucket: 'news-3d5f9.appspot.com',
    androidClientId: '393420910142-19o4o10mj56sj14e2gs2g1t5g2js8me2.apps.googleusercontent.com',
    iosClientId: '393420910142-2hdtrb4aiftsv3d4mci239lje6rdchoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXA6HxURDrX5AexVtHCQfR95O4LgeyxmM',
    appId: '1:393420910142:ios:1579257a746300515a2b6f',
    messagingSenderId: '393420910142',
    projectId: 'news-3d5f9',
    storageBucket: 'news-3d5f9.appspot.com',
    androidClientId: '393420910142-19o4o10mj56sj14e2gs2g1t5g2js8me2.apps.googleusercontent.com',
    iosClientId: '393420910142-2hdtrb4aiftsv3d4mci239lje6rdchoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJTZdtENx2e4QpJXXK-Sb3yIUdrv89ZmU',
    appId: '1:393420910142:web:b735bcb1d40bacf65a2b6f',
    messagingSenderId: '393420910142',
    projectId: 'news-3d5f9',
    authDomain: 'news-3d5f9.firebaseapp.com',
    storageBucket: 'news-3d5f9.appspot.com',
  );

}